version: "3.4"
services:
  doh-server:
    image: dnsoverhttpsdev/doh-server:latest
    volumes:
      - ./doh-server:/etc/doh-server
    depends_on:
      - bind9
    restart: always
    networks:
      dns:
        ipv4_address: 10.40.0.10
  bind9:
    image: resystit/bind9:latest
    volumes:
      - ./bind9/named.conf:/etc/bind/named.conf
      - ./bind9/zones:/etc/bind/zones
      - ./bind9/named.conf.local:/etc/bind/named.conf.local
      - ./bind9/named.conf.options:/etc/bind/named.conf.options
      - bind9:/etc/bind
    restart: always
    networks:
      dns:
        ipv4_address: 10.40.0.30
    ports:
      - "53:53/udp"
      - "53:53/tcp"
volumes:
  bind9:
networks:
  dns:
    driver: bridge
    ipam:
      config:
        - subnet: 10.40.0.0/16