version: "3.4"
services:
  doh-server:
    image: dnsoverhttpsdev/doh-server:latest
    volumes:
      - ./doh-server:/etc/doh-server
    depends_on:
      - bind9
    restart: always
    networks:
      dns:
        ipv4_address: 10.40.0.10
  doh-client:
    image: dnsoverhttpsdev/doh-client:latest
    volumes:
      - ./doh-client:/etc/doh-client
    restart: always
    networks:
      dns:
        ipv4_address: 10.40.0.20
  bind9:
    image: resystit/bind9:latest
    volumes:
      - ./bind9/named.doh-client.conf:/etc/bind/named.conf
      - ./bind9/zones:/etc/bind/zones
      - ./bind9/named.conf.local:/etc/bind/named.conf.local
      - ./bind9/named.conf.options:/etc/bind/named.conf.options
      - bind9:/etc/bind
    depends_on:
      - doh-client
    restart: always
    networks:
      dns:
        ipv4_address: 10.40.0.30
    ports:
      - "53:53/udp"
      - "53:53/tcp"
  nginx:
    image: nginx:1.15.9-alpine
    volumes:
      - ./nginx:/etc/nginx:rw
      - /etc/letsencrypt:/etc/letsencrypt
      - ./dhparam:/etc/dhparam
      - ./webroot:/var/www/webroot
    depends_on:
      - doh-server
    restart: always
    networks:
      dns:
        ipv4_address: 10.40.0.40
    ports:
      - "80:80"
      - "443:443"
      - "853:853"
volumes:
  bind9:
networks:
  dns:
    driver: bridge
    ipam:
      config:
        - subnet: 10.40.0.0/16